`timescale 1ns / 1ps

module soc_top (
    input  wire clk,
    input  wire rst,
    output wire led_out   // <-- real FPGA-visible output
);

    // -------------------------
    // Wires between core and memories
    // -------------------------
    wire [31:0] instr_addr;
    wire [31:0] instr;

    wire [31:0] data_addr;
    wire [31:0] data_wdata;
    wire [31:0] data_rdata;
    wire        data_we;
    wire        data_re;

    // -------------------------
    // Instantiate core
    // -------------------------
    riscv_core u_core (
        .clk(clk),
        .rst(rst),
        .instr_addr(instr_addr),
        .instr(instr),
        .data_addr(data_addr),
        .data_wdata(data_wdata),
        .data_rdata(data_rdata),
        .data_we(data_we),
        .data_re(data_re)
    );

    // -------------------------
    // Instruction memory (ROM), BYTE addressed
    // Matches objcopy -O verilog output (byte-by-byte)
    // -------------------------
    reg [7:0] imem[0:1023];          // 1 KB = 1024 bytes

    // PC is a byte address. Fetch 4 bytes: [PC+3:PC]
    wire [9:0] pc_byte_addr = instr_addr[9:0];  // up to 1024 bytes
    assign instr = { imem[pc_byte_addr + 10'd3],
                     imem[pc_byte_addr + 10'd2],
                     imem[pc_byte_addr + 10'd1],
                     imem[pc_byte_addr + 10'd0] };

    integer i;
    initial begin
        // Initialize bytes to 0x13 (low byte of ADDI x0,x0,0)
        for (i = 0; i < 1024; i = i + 1)
            imem[i] = 8'h13;

        // Load bytes from HEX file generated by objcopy
        $readmemh("sw/program.hex", imem);
    end

    // -------------------------
    // Data memory + UART address decoding
    // RAM: addresses 0x00000000 - 0x0000003F (64 bytes)
    // UART TX: address 0x00000080
    // -------------------------
    wire sel_ram  = (data_addr[7:6] == 2'b00);     // 0x00 - 0x3F (roughly)
    wire sel_uart = (data_addr == 32'h00000080);

    wire [31:0] ram_rdata;

    data_mem u_dmem (
        .clk(clk),
        .we(data_we & sel_ram),
        .re(data_re & sel_ram),
        .addr(data_addr),
        .wdata(data_wdata),
        .rdata(ram_rdata)
    );

    uart_sim u_uart (
        .clk(clk),
        .we(data_we & sel_uart),
        .addr(data_addr),
        .wdata(data_wdata)
    );

    // -------------------------
    // Dummy LED toggle on UART write (to keep logic during synthesis)
    // -------------------------
    reg led_reg = 1'b0;

    always @(posedge clk) begin
        if (rst)
            led_reg <= 1'b0;
        else if (data_we & sel_uart)
            led_reg <= ~led_reg;   // toggle on each UART write
    end

    assign led_out = led_reg;

    // Data readback to core
    assign data_rdata = sel_ram ? ram_rdata : 32'b0;  // UART read returns 0

endmodule
